services:
  auction-db:
    image: postgres:latest
    container_name: auction-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespw
      POSTGRES_DB: auctiondb
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_auction-db:/var/lib/postgresql/
volumes:
  postgres_auction-db: